### ISSUE TITLE
Could not find a matching version of package optidash-ai/optidash-laravel.

### ISSUE THREAD

**Issue by adampatterson** [optidash-ai/optidash-laravel#1]
I ran `composer require optidash-ai/optidash-laravel` 

I am using Laravel 7 and PHP 7.3

**Comment by matylla** [comment]
I'm on it.

**Comment by matylla** [comment]
Hey Adam,

Please use `optidash/laravel` as package name. I will update the docs now. Also, I've just pushed an updated verstion `1.0.1` so please be sure to clear composer's cache:

```
composer clear-cache
composer require optidash/laravel
```

**Comment by adampatterson** [comment]
Works, thanks!

**Comment by matylla** [comment]
Please be advised, I am currently updating the underlying `optidash-php` SDK. I will drop you a line when it's done.

**Comment by matylla** [comment]
Okay, `optidash/laravel` now uses `optidash/optidash` as its main PHP dependency in version `1.0.2`. Please open another issue if anything doesn't seem to be working as expected.

**Comment by adampatterson** [comment]
@matylla I was wondering if this is still the ideal package to use with laravel?

I ran into an install problem with the recent release of Laravel 10.

**Comment by matylla** [comment]
Hey @adampatterson,

thanks for your report. Can you please provide more context or (ideally) logs from your application? I will try to build against Laravel 10 tomorrow and solve the issue.

**Comment by adampatterson** [comment]
@matylla 

I don't even see where the package is requiring Laravel at all 🤷‍♂️

```shell
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - optidash/laravel 1.0.0 requires laravel/framework ^5.0|^6.0 -> found laravel/framework[v5.0.0, ..., v5.8.38, v6.0.0, ..., v6.20.44] but it conflicts with your root composer.json require (^10.0).
    - optidash/laravel 1.0.1 requires optidash/optidash dev-master -> found optidash/optidash[dev-master] but it does not match your minimum-stability.
    - Root composer.json requires optidash/laravel * -> satisfiable by optidash/laravel[1.0.0, 1.0.1].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require optidash/laravel:*" to figure out if any version is installable, or "composer require optidash/laravel:^2.1" if you know which you need.
```

**Comment by matylla** [comment]
@adampatterson 

I've just pushed version `1.0.2` of this package. Can you install that version and see if it fixes the problem?

**Comment by adampatterson** [comment]
Closer:

As part of the Laravel 10 upgrade steps it recommends to change the minimum stability to stable from dev.

```shell
Problem 1
    - Root composer.json requires optidash/laravel 1.0.2 -> satisfiable by optidash/laravel[1.0.2].
    - optidash/laravel 1.0.2 requires optidash/optidash dev-master -> found optidash/optidash[dev-master] but it does not match your minimum-stability.
```

I did have to run `composer require optidash/laravel:1.0.2` as `composer require optidash/laravel` resulted in the same error.
